<h2><?php echo Zend_Registry::get('translate')->_('admin.empresa.new.email_confirmation.title'); ?> {{nome}}</h2>
<br />
<?php echo Zend_Registry::get('translate')->_('admin.empresa.new.email_confirmation.message'); ?>
<br />
<br />
<a href="<?php echo $this->serverUrl(); ?><?php echo $this->baseUrl(); ?>/empresa">
    <?php echo Zend_Registry::get('translate')->_('admin.empresa.new.email_confirmation.link_authentication'); ?>
</a>
<br /><br />