<h2><?php echo Zend_Registry::get('translate')->_('admin.afiliado.new.email_confirmation.title'); ?></h2>
<br />
<?php echo Zend_Registry::get('translate')->_('admin.afiliado.new.email_confirmation.message'); ?>
<br />
<br />
<?php echo Zend_Registry::get('translate')->_('admin.afiliado.new.email_confirmation.numero_cartao'); ?>: {{numero_cartao}}
<br />
<?php echo Zend_Registry::get('translate')->_('admin.afiliado.new.email_confirmation.login'); ?>: {{login}}
<br />
<?php echo Zend_Registry::get('translate')->_('admin.afiliado.new.email_confirmation.senha'); ?>: {{senha}}
<br />
<a href="<?php echo $this->serverUrl(); ?><?php echo $this->baseUrl(); ?>/">
    <?php echo $this->serverUrl(); ?><?php echo $this->baseUrl(); ?>/
</a>
<br /><br />